FROM docker.elastic.co/elasticsearch/elasticsearch:8.11.0
MAINTAINER lilu 
RUN sh -c  'echo y | /usr/share/elasticsearch/bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v8.11.0/elasticsearch-analysis-ik-8.11.0.zip'

